### ISSUE TITLE
What about LDC's for method handles?

### ISSUE THREAD

**Issue by mdxd44** [radioegor146/native-obfuscator#66]
Are there any plans to support method handles for ldc nodes? For example sample, it's enough to take the obfuscation of references from zkm
```
java.lang.UnsupportedOperationException
        at by.radioegor146.instructions.LdcHandler.process(LdcHandler.java:75)
        at by.radioegor146.instructions.LdcHandler.process(LdcHandler.java:8)
        at by.radioegor146.instructions.GenericInstructionHandler.accept(GenericInstructionHandler.java:58)
        at by.radioegor146.instructions.InstructionHandlerContainer.accept(InstructionHandlerContainer.java:17)
        at by.radioegor146.MethodProcessor.processMethod(MethodProcessor.java:256)
        at by.radioegor146.NativeObfuscator.lambda$process$8(NativeObfuscator.java:246)
        at java.base/java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:559)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at by.radioegor146.NativeObfuscator.process(NativeObfuscator.java:148)
        at by.radioegor146.Main$NativeObfuscatorRunner.call(Main.java:71)
        at by.radioegor146.Main$NativeObfuscatorRunner.call(Main.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at by.radioegor146.Main.main(Main.java:80)
```

`System.out.println("Handle: \"" + cst + "\"");` output:
```
Handle: "ru/mdxd44/packagehere/?.a(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/invoke/MutableCallSite;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/Object; (6)"
```

(this is a generated bridge method by zkm for calling methods i guess)
![изображение](https://github.com/radioegor146/native-obfuscator/assets/67416904/d2db94bb-e178-498c-a304-1dd60ca893f7)

**Comment by radioegor146** [comment]
Will work on it, now it seams feasible

**Comment by radioegor146** [comment]
Can you provide sample jar to test it?

**Comment by radioegor146** [comment]
So it looks like that this stuff was implemented but still not used. Try with the new release.

**Comment by mdxd44** [comment]
I'm sorry for late answer.
[example.zip](https://github.com/radioegor146/native-obfuscator/files/12646031/example.zip)

**Comment by mdxd44** [comment]
Apparently it works
![изображение](https://github.com/radioegor146/native-obfuscator/assets/67416904/93a5435e-295e-4243-ad75-38c63f1c522b)
