### ISSUE TITLE
Failed to open lib file: /native0/x64-windows.dll

### ISSUE THREAD

**Issue by Stone-72** [radioegor146/native-obfuscator#82]
2024-07-07 12:10:59.085 [Nukkit] ERROR - Throwing
java.lang.UnsatisfiedLinkError: Failed to open lib file: /native0/x64-windows.dll
	at native0.Loader.<clinit>(synthetic:62) ~[?:?]
	at org.stone72.WasteAC.<clinit>(WasteAC.java) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:28) ~[patched.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:214) ~[patched.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:174) ~[patched.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:322) ~[patched.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:241) ~[patched.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:229) ~[patched.jar:?]
	at cn.nukkit.Server.<init>(Server.java:147) ~[patched.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:21) ~[patched.jar:?]
	at nukkit.pm1e.launcher.Main.lambda$start$0(Main.java:71) ~[?:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by VitaminB8964** [comment]
Maybe,you didn't copy the dll file to xxx.jar/native0/

**Comment by radioegor146** [comment]
Closed due to inactivity
